#!/usr/bin/env node
/**
 * Inline OpenAPI YAML into a TypeScript file.
 * Usage: node scripts/inline-openapi.js <yaml-path> <output-ts-path>
 * From repo root: node apps/api/scripts/inline-openapi.js docs/api/openapi.yaml apps/api/src/openapi-spec.ts
 * From Docker /app: node scripts/inline-openapi.js openapi.yaml src/openapi-spec.ts
 */
const fs = require("fs");
const path = require("path");

const [yamlPath, outputPath] = process.argv.slice(2);
const inputPath = yamlPath ? path.resolve(process.cwd(), yamlPath) : path.resolve(process.cwd(), "docs/api/openapi.yaml");
const outPath = outputPath ? path.resolve(process.cwd(), outputPath) : path.resolve(process.cwd(), "apps/api/src/openapi-spec.ts");

if (!fs.existsSync(inputPath)) {
  console.error(`Error: YAML file not found: ${inputPath}`);
  process.exit(1);
}

const yamlContent = fs.readFileSync(inputPath, "utf8");
const escaped = yamlContent.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
const tsContent = `/** Generated by scripts/inline-openapi.js — do not edit */\nexport const openApiYaml = \`${escaped}\`;\n`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, tsContent, "utf8");
console.log("Generated", outPath, "from", inputPath);
