/**
 * Inlines docs/api/openapi.yaml into a TS module so the Worker can serve it
 * without filesystem access. Run from repo root or from apps/api with paths.
 *
 * Usage:
 *   node apps/api/scripts/inline-openapi.js docs/api/openapi.yaml apps/api/src/openapi-spec.ts
 *   (from Docker /app): node scripts/inline-openapi.js openapi.yaml src/openapi-spec.ts
 */
const fs = require("fs");
const path = require("path");

const inputPath = path.resolve(process.cwd(), process.argv[2] || "docs/api/openapi.yaml");
const outputPath = path.resolve(process.cwd(), process.argv[3] || "apps/api/src/openapi-spec.ts");

const yaml = fs.readFileSync(inputPath, "utf8");
const escaped = yaml.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
const out = `/** Generated by scripts/inline-openapi.js — do not edit */\nexport const openApiYaml = \`${escaped}\`;\n`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, out, "utf8");
console.log("Wrote", outputPath);
